.gitignore
tor/core/mentions.py

Fixes [issue #17](https://waffle.io/itsthejoker/TranscribersOfReddit/cards/5920e366a1a2b700261ba314)

#17 - Ignore username mentions by OPs

---

tor/core/user_interaction.py

Allows the CoC notifications we receive to have a clickable link in them now. This change has been okay'd as usable by Sam.

Slack CoC Notification update

---

CHANGELOG.md
tor/main.py

- Debug mode
- Production mode user reference in praw.ini

Defers more things to environment variables

---

tor/core/inbox.py

Closes #33 
I also removed two unused imports, and some minor formatting.

Send message to Slack when getting unknown replies, and minor formatting

---

tor/helpers/flair.py

This mirrors the solution we already have in place in Discord to the actual subreddit. We've heard over and over again that people really like this extra thing they can work towards, so this just writes the appropriate css class when their flair is updated. 
The CSS is already in place on the subreddit.

Use Discord Flair Colors in Subreddit

---

tor/helpers/flair.py

#blamejoker
The issue came from #76

Removed unused import

---

tor/core/admin_commands.py
tor/core/inbox.py

Closes #16 
TODO:
Do you guys want me to add a CHANGELOG entry?

Add blacklisting people

---

tor/core/admin_commands.py
tor/core/commands.csv
tor/core/commands.json
tor/core/inbox.py

New command system

---

CHANGELOG.md
tor/core/inbox.py
tor/core/user_interaction.py

Got a "done" comment today where the transcriber had added the URL of their transcription - which happened to include the word "fuck" so the "done" was not processed.
https://www.reddit.com/r/TranscribersOfReddit/comments/7rs9yq/trollxchromosomes_image_fuckboys_be_like/dszh158/

Update user commands structure

---

tor/strings/posts.py

Rearrange the rules comment a little bit. Had a newbie get confused by the current layout, so this fixes that issue.
https://www.reddit.com/r/TranscribersOfReddit/comments/83kmp4/me_irl_image_me_irl/dviph2j/?context=3&utm_content=context&utm_medium=message&utm_source=reddit&utm_name=frontpage

update verbiage of rules comment

---

tor/core/user_interaction.py
tor/helpers/flair.py

https://www.reddit.com/r/redditdev/comments/87wwl8/reddit_appears_to_have_slightly_changed_how_the/

fix flair detection

---

tor/core/user_interaction.py

Move new volunteer notifications to their own channel. And make the message more fun.

update code of conduct channel and make message more fun

---

tor/core/inbox.py
tor/core/user_interaction.py

Add direct links to send_to_modchat messages

---

tor/core/user_interaction.py

Stop things from spamming #general now that we're pretty sure that everything works as expected.

move message to appropriate channel

---

CHANGELOG.md
tor/core/user_interaction.py

This is to address a regression introduced in #146

Gracefully degrade if mods message us

---

.flake8
CHANGELOG.md

Signed-off-by: Joe Kaufeld <joe.kaufeld@gmail.com>

ignore W503 errors

---

.github/workflows/automated-tests.yml
CONTRIBUTING.md
README.md

Another example of an administrative update. Not a whole lot that needs to be mentioned in the changelog

Updates docs on how to contribute to the repository

---

tor/core/blossom_wrapper.py
tor/core/helpers.py
tor/core/user_interaction.py
tor/strings/en_US.yml

Note that as long as #188 is open, this PR shows multiple commits. For review, please only focus on the commits not in #188, as these will already be reviewed there.

Add Blossom integration for the "Unclaim" message processing

---

tor/core/blossom_wrapper.py
tor/core/inbox.py
tor/core/user_interaction.py
tor/core/validation.py
tor/helpers/flair.py
tor/strings/en_US.yml

In this PR the integration is done for the "Done" procedure. Note that the methods used within the old workflow are also refactored within this PR.

Add Blossom integration for the "Done" message processing

---

test/core/test_admin_commands.py
test/validation/test_formatting_validation.py
test/validation/test_helpers.py
tor/core/__init__.py
tor/core/inbox.py
tor/core/user_interaction.py
tor/strings/en_US.yml
tor/validation/__init__.py
tor/validation/formatting_issues.py
tor/validation/formatting_validation.py
tor/validation/helpers.py
tor/validation/transcription_validation.py

This PR fixes several issues that persisted with the formatting check:
- Improved separator detection with trailing spaces
- Improved separator as heading detection with spaces
- Fixed formatting of issue messages (hopefully)
- Fixed URL in Slack notifications for formatting issues
- Fixed duplicated footer for some bot replies
- Fixed override not bypassing transcription check
⚠️ CAREFUL! This reverts some of the revisions applied previously, some files that we need might be automatically deleted when merging! ⚠️

Fix formatting issue check

---

test/validation/test_formatting_validation.py
tor/validation/formatting_validation.py

Fix false positive on multi-heading (i.e. ## Heading)

---

tor/core/user_interaction.py
tor/strings/en_US.yml

Closes #274.
This adds a random tip to the `claim` response to slowly introduce the volunteers to new concepts.

Add random tip to `claim` response

---

tor/helpers/flair.py

This adds Pink (25 gamma) and Sapphire (20,000 gamma) as flair ranks.

Add Pink and Sapphire ranks

---

.flake8
tor/__init__.py
tor/cli/main.py
tor/core/__init__.py
tor/core/admin_commands.py
tor/core/config.py
tor/core/helpers.py
tor/core/inbox.py
tor/core/initialize.py
tor/core/posts.py
tor/core/user_interaction.py
tor/core/users.py
tor/helpers/flair.py
tor/helpers/threaded_worker.py
tor/helpers/youtube.py
tor/strings/__init__.py
tor/validation/formatting_validation.py

This PR simply runs Black on the main codebase. There should be no functional changes whatsoever.

Blacken all the things!

---

test/validation/test_formatting_validation.py
test/validation/transcriptions/valid/facebook_example_new_footer.txt
test/validation/transcriptions/valid/reddit_post_template_new_footer.txt
test/validation/transcriptions/valid/tumblr_template_new_footer.txt
tor/validation/formatting_validation.py

The new footer removes the 'for Reddit' part, to avoid misunderstandings who we work for.
This PR makes sure that the formatting check allows this new footer.

Adjust formatting checks to allow new footer

---

tor/core/config.py
tor/core/initialize.py
tor/core/posts.py

Closes #289.
The audio format used an outdated wiki page, the other format was redundant and also used an outdated page.

Update wiki links

---

test/validation/test_formatting_validation.py
tor/strings/en_US.yml
tor/validation/formatting_issues.py
tor/validation/formatting_validation.py

Add check for double-spaced and escaped line break

---

tor/core/helpers.py
tor/core/user_interaction.py
tor/strings/en_US.yml

Closes #316
We now don't check the reports anymore.
Instead, we always check if the partner post has been removed or marked as NSFW on the partner sub.
If yes, we replicate that state to ToR and Blossom.

Improve post handling on unclaim

---

tor/strings/en_US.yml

Updated the mod application form link

New Mod App. Form

---

tor/core/__init__.py

adding "calim", and "dib" as acceptable claim phrases

---

tor/strings/en_US.yml

Added CtQ info into bot's claim and done responds.

CtQ bot respond

---

tor/strings/en_US.yml

Added a space between the emojis and the messages.

Typo fix to ctq bot respond

---

tor/strings/en_US.yml

Deleted CtQ advertisement parts from bot's responds to successful "claim" and "done"  comments.

Deleted CtQ Promo

---

.github/workflows/automated-tests.yml
tor/cli/main.py

Fix bug related to loading .env file when packaged.

Fix env loading

---

.github/workflows/automated-tests.yml
poetry.lock
pyproject.toml
tor/core/user_interaction.py
tor/strings/en_US.yml

- Renamed `blacklisted` to `blocked`
- Changed response message to
> ⛔ Sorry you can't transcribe at this time. Please message the mods through modmail.

Update message when user is blocked

---

.github/workflows/build_and_release.yml
.github/workflows/build_and_test.yml
poetry.lock
pyproject.toml

Nothing fancy. Just letting this build again

fix broken poetry2setup

---

tor/helpers/flair.py
tor/test/helpers/test_flair_helpers.py

Adds Garnet as 30,000+ rank color.

Add Garnet role color

---

tor/helpers/threaded_worker.py

With this PR, the queue will stop being populated with posts starting at 2023-07-01 at 00:00 UTC.
This allows the remaining posts to be transcribed so that we finish with a cleared queue.

Stop populating the queue with posts once the sub is closed

---

tor/core/__init__.py

It's essential for the success of the project.

Add more, and very important, unclaim phrases
