GrafeasGroup/tor

tor/__init__.py
tor/core/initialize.py
tor/core/posts.py

Subreddits with an upvote threshold can now be stored in `wiki/subreddits/upvote-filtered` in the following csv format:
me_irl,15
4chan,5
`wiki/subreddits/upvote-filtered/filter` becomes useless.

per-subreddit upvote threshold

---

README.md
setup.py
tor/archiver.py
tor/main.py
tor/ocr.py

See changes to README for how to invoke the bots.
Realistically, this is backwards compatible with the `python tor/archiver.py` format, but this makes it so on `pip install` it adds the CLI tool to the PATH and hardcodes the version of python in the shebang. In short, it means python2 and python3 CLI tools can coexist in PATH. You also don't have to know what version of python to use.

Converts to standalone commands via console_scripts

---

CHANGELOG.md
README.md
setup.py

Looks like we haven't been too diligent on updating the changelog for each release. Now all version changes (except one flub with `2.6.14` -> `2.6.1` -> `2.7.0`) are [tagged in git](https://github.com/TranscribersOfReddit/TranscribersOfReddit/tags).
This PR is a followup by attempting to describe the changes between `v2.7.1` -> `v3.0.0` and between `v3.0.0` -> `v3.0.1`
Also prunes stale `console_scripts` in `setup.py`.

Updates changelog to include missed releases

---

tor/core/inbox.py
tor/core/mentions.py
tor/strings/posts.py
tor/strings/responses.py

Right now, if you ping u/transcribersofreddit, it will automatically format and create a post on r/ToR. Due to the possibility of the bot being banned in any sub where it's called, we're converting this to PM a user instead, telling them to please make a post on r/DescriptionPlease.
Once they post there, it will automatically get crossposted to r/ToR as part of the normal operations. This also opens up a new avenue and some better integration with r/blind and their members.

The PM Update: Convert username mentions to PMs instead

---

tor/core/user_interaction.py

Adds in some code to better debug the `DELETED_COMMENT` exception that keeps getting thrown. It should help with figuring out the type of the exception being thrown, at least, so we can catch it in a more appropriate spot.
I decided to forego the usual addition to `CHANGELOG.md` due to this being debugging code that will/should be removed later.

Adds deleted comment logging

---

CHANGELOG.md
tor/core/user_interaction.py

Pretty self-explanatory. Any time we try to do a `post.reply()`, we should be guarding for APIException of type `DELETED_COMMENT` like this. In most cases it should be safe to just drop it.

Guard every reply against DELETED_COMMENT

---

CHANGELOG.md
tor/core/inbox.py

Right now, the inbox pulls in the default PRAW method, which is newest to oldest. If the bot is offline for some amount of time and responses are allowed to build up, that means that "done" comments will be processed before "claim" comments.
This change pulls all the unread messages, puts them in a list, inverts the list, and then processes from oldest to newest.

Partner PR for 3.1.0: Invert Inbox

---

tor/core/inbox.py

This covers the use case where someone tries to "unclaim" a post, while simultaneously laying the ground-work for notifying mods in slack if a comment needs mod-attention.

Mod help needed comments

---

tor/core/inbox.py
tor/helpers/flair.py

This adds a slack message for meta posts, and slightly improves the formatting of the slack messages for unhandled replies.

Send meta posts to slack

---

CHANGELOG.md
tor/core/inbox.py
tor/core/user_interaction.py

Of all the various typos we see, "deno" is by far the most popular way to butcher "done". This minor update allows this to process as normal.

Allows "deno" to start the completion process

---

setup.py
tor/core/validation.py

If a user actually uses their feed for more than just comment history (it's possible nowadays to have your own subreddit-like experience on your user profile), we skip it. This became necessary when we wouldn't respond to `done` with the new history checker functionality.

History checker blows up on pinned submissions

---

CHANGELOG.md
tor/helpers/youtube.py

This should prevent us from sending off a transcription request if the video id wasn't able to be gleaned from the URL. If nothing else, we can do logging of the url we weren't able to decode in order to refine the video id extraction method, but 🤷‍♂️

Fixes video id of `None` errors from YouTube

---

CHANGELOG.md
tor/core/validation.py

So apparently the history validation doesn't work properly when someone has submissions stickied to their profile. I was unable to replicate this, but it should be fixed anyway by this.

Change history validation to only look for comments

---

tor/core/admin_commands.py
tor/core/inbox.py
tor/core/user_interaction.py
tor/core/validation.py
tor/helpers/flair.py

This PR removes slack-specific language and replaces it with the more generic "modchat". This _must_ be merged with the corresponding PR to tor_core.

updated for modchat

---

tor/helpers/threaded_worker.py

We sped up checking for new posts so much that we're kind of hammering Reddit's API right now. This change makes it so that we only check for new posts once every 45 seconds and has a matching PR in tor_core.

Add in some delay for checking for new posts

---

tor/helpers/reddit_ids.py

The incomplete post check, while great in theory, causes more problems than it's worth because Reddit doesn't like it when we retry posting actions. This causes the bot to continue to try resubmitting the same job over and over and having it continually fail, sending the bot into a never-ending failure state.
```
Jul 09 03:27:26 tor_moderator[2972]: WARNING | is_valid | Incomplete post found! ID: t3_8x6jp2
Jul 09 03:27:26 tor_moderator[2972]: INFO | process_post | Posting call for transcription on ID t3_8x6jp2 posted by needco
Jul 09 03:27:26 tor_moderator[2972]: WARNING | run_until_dead | received 403 HTTP response - Issue communicating with Reddit. Sleeping for 60s!
Jul 09 03:28:30 tor_moderator[2972]: WARNING | is_valid | Incomplete post found! ID: t3_8x6jp2
Jul 09 03:28:30 …
```

Removed check for incomplete posts

---

tor/core/validation.py

Just adds a small check to stop people from rewriting the footer and forcing them to use the markdown abomination that is our current footer.

make validation look for a properly formatted footer

---

tor/core/inbox.py
tor/helpers/flair.py

Mainly changes the meta post notification to actually link to the post rather than the attached URL. Also includes the body of messages without an author, just like with unhandled messages.

Update slack messages a bit

---

tor/strings/posts.py

This correction should correct OurInterface's remark about the typo error ([link](https://www.reddit.com/message/messages/enexce)).

Fix typo error in "Rules" comment

---

CODE_OF_MERIT.md

One of the most important aspects of our work, both as an organization and in the codebases, is to be accepting of different viewpoints which can further our mutual mission. This naturally leads us in pursuit of some guidelines to govern contributor behavior and act as a higher set of rules with which we should use to resolve conflict. 
While a large number of projects include the Contributor Covenant as a guideline for contributor behavior, there are concerning issues that lead to multiple interpretations of the document and a lack of defined boundaries -- if a code of conduct is open to interpretation, then it is not strict enough.
The below is a modified version of the Code of Merit, slightly updated with an addition from the American Librarian Association (ALA), whose ethics …

RFC: Add Code of Merit, modified for GG

---

tor/strings/en_US.yml

The bot will tell people about "Unclaim" after their claim (at the same time as the "Done"). It should help new (and older) transcribers to unclaim posts.

Add "Unclaim" text

---

CHANGELOG.md
tor/core/inbox.py
tor/core/user_interaction.py
tor/core/validation.py
tor/strings/en_US.yml

Right now we can detect transcriptions when they've been put in the r/ToR thread, but not if they're done using the new reddit formatter. This PR extends the current functionality to include the WYSIWYG editor mangling our footer.
Signed-off-by: Joe Kaufeld <joe.kaufeld@gmail.com>

documentation update and extend detecting transcriptions in the wrong place

---

.github/workflows/publish.yml

Actions included:
- Publish the `pip install`-able artifacts to a GitHub Release whenever a version tag is pushed

GitHub Actions

---

CHANGELOG.md
tor/core/helpers.py
tor/core/inbox.py
tor/core/mentions.py

Logic was discussed in modchat, but comparison of the Comment's subreddit will determine if it was a username mention or a directive to the bot (if not in the ToR subreddit, must be a mention).
Also includes some other cleanup stuff, such as relying on redis instead of python for if member of the `blacklist` set.

Lessens dependence on English language

---

CHANGELOG.md
tor/core/inbox.py
tor/core/user_interaction.py

Apparently there's a way to flag a post for moderation while having the report itself be null, which makes the bot bomb out. Better to err on the side of caution and just have the bot skip over the report in favor of a human looking at it than try to handle it automatically.

Fixes crash if post has report with body 'null'

---

README.md

See official docs: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
Purely administrative, so I'm skipping the changelog entry

Swaps out Travis CI badge for GitHub Actions status

---

tor/core/blossom_wrapper.py
tor/core/user_interaction.py
tor/strings/en_US.yml

Add integration for the "claim" message processing. Note that this removes the need for the `already_completed` message, as this falls under the error message of `already_claimed`. Please also note #187 on this topic.

Add Blossom integration for the "Claim" message processing

---

.github/workflows/automated-tests.yml

The use of new features means that the automated tests can't use older versions of python anymore -- this limits the only usable version to 3.8 (and we can expand outwards once 3.9 is released -- I would have added the nightly build, but github actions only supports full releases of python).
Signed-off-by: Joe Kaufeld <joe.kaufeld@gmail.com>

remove older (incompatible) versions of python

---

poetry.lock
pyproject.toml
tor/core/blossom_wrapper.py

Adds `black` as a development dependency so that we can use it.
The primary fix here is that it solves an error with resolving types in the dataclass, namely allowing None as a valid option since it's initialized that way.
Signed-off-by: Joe Kaufeld <joe.kaufeld@gmail.com>

fix type error for blossom_wrapper

---

tor/strings/en_US.yml

Users cannot copy/paste the footer using reddit mobile. Added a note in the footer comment about it.

Added note about footer on Reddit Mobile

---

tor/helpers/flair.py

Add official names for the "Ruby+" and "Ruby++" flairs.

Add official names for Ruby+ and Ruby++

---

pyproject.toml
tor/__init__.py
tor/core/validation.py

Wraps the call to load the target submission with a check to get a 403 forbidden, which is what Reddit returns through the API if you try and access a specific ID behind a private subreddit. This new behavior will fall through to the author check and, if successful, will not trigger the slack ping about a removed post.

Patch breaking bug for private subreddits

---

tor/strings/en_US.yml

We have had a lot of new volunteers writing "I agree" or "accept" instead of "I accept", which is a problem since their claim won't be processed. I added an explicit warning about that in the message of the bot introducing the Code of Conduct.

Add warning about "I agree"

---

tor/core/initialize.py

So we have three video format pages:
* /examples/video
* /format/video
* /formats/video
Of all of them, the one that's actually updated and linked to on the sub sidebar is /format**s**/video/, so this change simply redirects the loaded wiki page to the one that's actually used. After this is deployed, we should decommission the other pages.

Update Video Format Page

---

tor/core/inbox.py

This moves the check for transcription replies infront of the checks for "fuck" and similar phrases. This fixes instances of transcriptions being posted on r/ToR that contain "fuck". They would result in a mod ping instead of telling the users to post on the partner sub.
**Note:** I haven't tested this, because I don't know how to. Probably a good idea to review this thoroughly.
Closes #214.

Do transcription reply detection before 'fuck' detection

---

tor/cli/main.py
tor/core/__init__.py
tor/core/admin_commands.py
tor/core/inbox.py
tor/core/user_interaction.py

This PR is fairly large for the actual number of material changes in it; most of it is `black` and various cleanups that I stumbled over while implementing this command. Full list of changes:
* update donor comment
* move all common string phrases to `tor/core/__init__.py` to allow importing from more than one place
* update `!override` to work on any source comment that is valid for claim or done, like `deno`
* don't attempt to send the "hey I don't respond to DMs" message to an account that doesn't exist (for the messages from reddit as a platform)
* add a `!debug` command that just prints out the Blossom object for the current submission. Should make the next step in debugging immediately obvious when working with a troublesome submission.

Add debug command

---

tor/core/helpers.py

The reason that unclaim isn't working right now is because the code expects a blossomstatus enum from the PATCH call (which honestly does make sense) but until @MaxVanDeursen's work on refactoring the wrapper is complete, the raw methods just return Requests objects. This PR addresses that issue; the fix was tested in prod and confirmed working.

Fix Unclaim

---

tor/core/helpers.py
tor/core/user_interaction.py

When trying to perform an override, the current process hinges on whether or not a transcription is found. If the transcription is removed (or doesn't exist) then the override will fail. This PR moves the actual "done" logic to a separate check to see if we find the transcription OR an override has been triggered.

closes #227: fix override breaking if no transcription is found

---

poetry.lock
tor/core/user_interaction.py

Found a bug in blossom-wrapper where something that was already claimed was being marked as already completed, and that has already been fixed in the wrapper. This PR makes the correct response return (instead of defaulting to "this has already been claimed") so that we have a better idea of when something explodes instead of it giving the wrong response.

Fix default response for claims to better identify iffy responses from Blossom

---

tor/core/helpers.py
tor/core/inbox.py

Something that the third party systems use is strings like "done -- this was an automated action". https://github.com/GrafeasGroup/tor/pull/228 accidentally broke that, so this PR reinstates that ability.

Allow claim, done, and unclaim with extra content

---

tor/core/helpers.py
tor/core/posts.py

For posts that were submitted before Blossom, it's entirely reasonable that Blossom won't know about them. Though this shouldn't _really_ happen, there is always the chance that it can and the logic that actually performed this is broken. This PR provides blossom with all the information it needs to create a new submission.

Fix handling submissions that Blossom doesn't recognize

---

tor/core/__init__.py

Since we've been seeing some additional new misspellings come through, seems like a reasonable idea to add them to the bot since it's pretty clear what they're trying to attempt.

Add more valid words for commands

---

tor/core/posts.py
tor/helpers/threaded_worker.py
tor/helpers/youtube.py

This feature is rarely used. It exploded on a partner subreddit this morning, and it seems like more trouble than it's worth for this feature, so this PR removes the ability for ToR to attempt to automatically detect human-written transcriptions on youtube videos.
By removing this, it also limits ToR to only posting in our subreddit; this functionality is the only one that allows ToR to venture beyond our walls.

Remove youtube transcript auto-detection feature

---

tor/cli/main.py

ToR is generating roughly 70% of all notifications on honeycomb.io, so this imposes the same rate limiting that we added for Blossom.

Turn on sampling for beeline

---

tor/core/user_interaction.py

Closes #241.
Sometimes, a transcription is not visible to the Reddit API a short time after posting it. This can lead to the bot not finding the transcription when the user replies `done` quickly. Volunteers has reported this problem to occur a lot more frequently after deploying Blossom.
With this PR, the bot will try to find the transcription again after a short delay if it's not visible already.

Retry finding the transcription once if it cannot be found

---

poetry.lock
pyproject.toml
tor/core/user_interaction.py
tor/strings/en_US.yml

Relevant issues: Closes #220, closes #187.
This properly handles the user trying to claim a post twice. Instead of saming that "someone" already claimed the post, it will tell the user that they already got the post. If another person claimed it, the bot will tell you who it was (without pinging them).
Additionally, this adds handling for the mass-claim prevention. When a user claimed to many posts, the bot will give them a list of submissions that they still need to complete.
⚠️  This change should be deployed immidiately **before** deploying GrafeasGroup/blossom#183 and GrafeasGroup/blossom#185. ⚠️ 
These PRs contain the API changes necessary for these responses.

Handle double claiming and mass claims

---

tor/core/user_interaction.py

This fixes that a variable for a Reddit comment was named `post` and fixes a faulty attribute access to get a comment link.

Fix variable naming and wrong link access on comment

---

tor/strings/en_US.yml

The localization key for the `heading_with_dashes` issue had the wrong name.
This caused the bot to crash when assembling the reply, resulting in the volunteer not being notified and spamming the mod Slack with messages.

Fix the bot crashing when a heading with dashes is detected

---

test/validation/test_formatting_validation.py
tor/strings/en_US.yml
tor/validation/formatting_issues.py
tor/validation/formatting_validation.py

Closes #254 
This adds automatic formatting checks for unescaped header markdown, e.g. \#username instead of \\\#username.

Add check for unescaped hashtags

---

test/validation/test_formatting_validation.py
test/validation/transcriptions/invalid/unescaped-heading.txt
tor/validation/formatting_validation.py

In relation to #263 
The check implemented in that PR wasn't actually called in the `check_formatting_issues` function.

Call unescaped heading check

---

tor/core/posts.py
tor/helpers/threaded_worker.py

Closes #196 
Mentions that the post has a Reddit image gallery (doesn't work for Imgur as far as I know) in the title of the ToR post, currently has the formatting as image formatting but it could be changed to have a different bot comment.
Works by checking if the `is_gallery` key is present in the JSON response Reddit returns, it's only present when the image is a gallery. [Example of data](http://img.theodorehua.dev/4IiAvdDs). 
The logic is all very simple but I haven't been able to test it locally.

Add title mention for Reddit galleries

---

test/validation/test_formatting_validation.py
tor/strings/en_US.yml
tor/validation/formatting_issues.py
tor/validation/formatting_validation.py

Closes #271 
The code checks if a header of valid type (Image, Video, or Audio) is present in the transcription, using the regex `\*<type>.*\*` (replace `<type>` with valid headers, such as `Image Transcription`) searching above the first separator.
The issue also suggested putting the exact header type the transcription should have in the issue message (e.g. post is an Video, then it should suggest the transcriber put `Video Transcription`).   
I don't really see a good way of doing this as the formatting testing and formatting issue message functions only receive the transcription as a string and not a Reddit or Blossom object (which could be used to get the type from the title or a parameter). I'm more than happy to get proved wrong though.

Add formatting check for missing or invalid header

---

test/validation/test_formatting_validation.py
test/validation/transcriptions/invalid/unescaped_username_subreddit.txt
test/validation/transcriptions/valid/reddit_comment_template.txt
test/validation/transcriptions/valid/reddit_post_template.txt
tor/strings/en_US.yml
tor/validation/formatting_issues.py
tor/validation/formatting_validation.py

Closes #248.
This adds automatic formatting checks for unescaped sub- and usernames, e.g. `u/username` instead of `u\/username`.
If the name is not escaped it pings the user, so we want to avoid that.

Add checks for unescaped sub- and usernames

---

test/validation/transcriptions/valid/377970.txt
tor/validation/formatting_validation.py

Closes #290.
This relaxes the separator detection to not require an empty line after the separator.
They should still render correctly on both old and new Reddit.
Some volunteers got confused when this got rejected (because they can't see the difference), so this should help with that.

Relax footer check to not require empty line after separator

---

test/core/test_helpers.py
tor/core/helpers.py
tor/core/posts.py

Closes #297.
This fixes the cloning of posts by reverting the encoding of `&`, `<` and `>`.
Otherwise, the post title might be too long for Blossom to handle.

Hotfix: Fix cloning of posts

---

tor/strings/en_US.yml

Closes #299.
The formatting check error message still included the old footer.
It has now be updated to the new one.

Update footer in formatting check message

---

CHANGELOG.md
tor/core/config.py
tor/helpers/flair.py

Closes #303 
Adds last_set_meta_flair_time to Config object.
last_set_meta_flair_time tracks the timestamp of the last reddit post processed by set_meta_flair_on_other_posts(). 
set_meta_flair_on_other_posts() will skip a post if the post's created_utc timestamp from reddit is before cfg.last_set_meta_flair_time. after processing all the posts, cfg.last_set_meta_flair_time is updated to newest posts created_utc timestamp.

Track timestamp of last reddit post before sending to mod chat

---

tor/core/helpers.py
tor/core/posts.py
tor/helpers/flair.py

Closes #278.
This contains two main changes:
- The flair template IDs are now provided via .env variables. This avoids the runtime overhead of determining the ID, which could potentially include API calls.
- When a new transcription is requested, the corresponding post is flaired directly when posting. This saves an API call and could prevent most cases of post duplication in the queue.
All in all, this should make the bot more robust, with the downside of us having to define the template IDs in advance.
Furtunately, this isn't hard to do at all.
:warning: This is a breaking change. The following variables have to be added to the `.env` file: :warning: 
- `UNCLAIMED_FLAIR_ID`
- `IN_PROGRESS_FLAIR_ID`
- `COMPLETED_FLAIR_ID`
- `META_FLAIR_ID`
- `DISREGARD_FLAIR_ID`
The bot should also be …

Rework submission flairing

---

test/validation/test_formatting_validation.py
tor/strings/en_US.yml
tor/validation/formatting_issues.py
tor/validation/formatting_validation.py

Closes #286 
This PR adds formatting for reference links, as outlined in the corresponding issue. From my own testing, the reference link formatting doesn't trigger on Reddit when there's text before it (i.e. `Text here [Test]: hello`), however to play it on the safe side considering Reddit's finnicky-ness, the regex I used will still trigger if there's text before. If that is unwanted, replace the regex with `^\[.*]:.*`.

Add reference links formatting check

---

test/validation/test_formatting_validation.py
tor/strings/en_US.yml
tor/validation/formatting_validation.py

Fixes #313 
This adds an anchor to check for the beginning of the text in the Invalid Header check, preventing text from coming before the header.

Disallow characters prior to the header

---

tor/strings/en_US.yml

This PR adds emojis to the bot's responses to make it more clear when something has gone wrong:
- A checkmark if the command has been executed successfully.
- A warning sign if something looks off.
- A no entry sign if the command failed.
- Some misc emojis for other things.
I also rephrased some responses and added a note about the `help` command in the error cases.

Add emoji indicators to the bot's responses

---

test/validation/test_formatting_validation.py
tor/strings/en_US.yml
tor/validation/formatting_validation.py

Ironically this PR started out because I got sick of reading "Sorry, I **can't find** your transcription on on the post." and morphed into more. Let me know if you want me to create two PRs for this instead since the only real .... connection between these changes is that I started out in the strings file and went from there.
For the reference links: We (QA) specifically tell volunteers not to bold names within square brackets; if they're within brackets they should be italicized instead. Also, personally, I'd mostly use the brackets for redaction rather than a user's name being omitted, so I changed that as well.

Update bot reply strings (reference links + "Sorry I can't find ...")

---

tor/core/inbox.py

Closes #329.
This adds a `!comment` command which simply makes the bot ignore the reply, such it doesn't send it to Slack as an unknown command.
This can be used if mods need to communicate with volunteers via top-level comments.

Add command to let the bot ignore a comment

---

tor/core/inbox.py
tor/strings/en_US.yml

Closes #332.
This adds the author and comment text to the Slack message sent when the user uses the `help` command.

Add author and comment text to help Slack message

---

tor/core/inbox.py
tor/strings/en_US.yml

Closes #352 
The response when a user posts their transcription as a comment on the Tor post now guides the transcribers to the partner post:
---
**OLD:**
The transcription should be made as a **top-level comment** on the post that you're working on transcribing.
For example, if the content is on r\/nicegirls, then the transcription should be commented as a reply to that submission on r\/nicegirls.
**NEW:**
The transcription should be made as a **top-level comment** on the \[post on r\/{sub_name}]({post_link}).

Update: Response to transcript on Tor post

---

CHANGELOG.md
tor/strings/en_US.yml

Closes #350:
> In the unescaped heading warning, the section that explains how to escape the heading doesn't have a backlash in its example. This fixes that.
Hoping I read the contribution guidelines right.

Add missing backslash in unescaped heading string

---

tor/core/helpers.py

Use `log.exception` to generate the full stack trace for uncaught exceptions.

Generate better exception logs

---

scripts/clear_submissions_from_queue.py
tor/core/helpers.py
tor/core/inbox.py
tor/core/posts.py
tor/core/user_interaction.py

Fix the error
```
Feb 23 10:48:16 localhost tor_moderator[8534]: ERROR | run_until_dead | 'BlossomResponse' object is not subscriptable`.
```
This was caused by a type error in the case that the app is trying to get a submission from Blossom that does not exist yet.
Additionally, all uncaught exceptions log the full stacktrace now.

Fix blossom response error
